name: Monthly Canary

on:
  schedule:
    - cron: "17 4 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  current-lock:
    uses: ./.github/workflows/candidate.yml
    with:
      stage: combined
